# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: profile-app
  template:
    metadata:
      labels:
        app: profile-app
    spec:
      containers:
      - name: profile-app
        image: profile-app:latest
        ports:
        - containerPort: 8080
